// <auto-generated />
namespace Biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class updatedlibroentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedlibroentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502020458175_updated libro entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
